# Generated by Django 5.2.15 on 2026-06-13 20:33

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import identity.domain.ids
import identity.domain.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.UUIDField(default=identity.domain.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.TextField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset')])),
                ('token_hash', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'user_tokens',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', identity.domain.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=identity.domain.ids.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('deleted_at__isnull', True)), name='users_email_uq'),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'kind'], name='user_tokens_user_kind_ix'),
        ),
        migrations.AddConstraint(
            model_name='usertoken',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('email_verification', 'password_reset'))), name='user_tokens_kind_ck'),
        ),
    ]
