# Generated by Django 5.2.15; hand-finished with the §4.1-4.2 CHECK regexes,
# Class H RLS for the hybrid tables + Class T RLS for the instance table
# (database-schema §9.5), and the §4.2 immutability trigger.

import catalog.domain.ids
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tenancy.domain.scoping
from django.db import migrations, models

from catalog.infra.rls import EnableHybridRowLevelSecurity
from catalog.infra.triggers import InstallManifestImmutability, PostgresOnlyRunSQL
from tenancy.infra.rls import EnableRowLevelSecurity

# database-schema §4.1/§4.2 — slug + semver CHECKs are Postgres regex matches (~),
# applied via RunSQL (Postgres-only; no-op on the SQLite unit lane, where the
# manifest grammar + app validation carry them).
_SLUG_CHECK = (
    "ALTER TABLE scenarios ADD CONSTRAINT scenarios_slug_ck "
    r"CHECK (slug ~ '^[a-z][a-z0-9_]{0,31}$');"
)
_SLUG_CHECK_DROP = "ALTER TABLE scenarios DROP CONSTRAINT IF EXISTS scenarios_slug_ck;"
_SEMVER_CHECK = (
    "ALTER TABLE scenario_definitions ADD CONSTRAINT scenario_defs_version_ck "
    r"CHECK (version ~ '^\d+\.\d+\.\d+$');"
)
_SEMVER_CHECK_DROP = (
    "ALTER TABLE scenario_definitions DROP CONSTRAINT IF EXISTS scenario_defs_version_ck;"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_api_key_auth_bootstrap_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=catalog.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField(default='')),
                ('visibility', models.TextField(choices=[('global', 'Global'), ('workspace', 'Workspace')])),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'scenarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('visibility__in', ('global', 'workspace'))), name='scenarios_visibility_ck'), models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'global'), ('workspace_id__isnull', True)), models.Q(('visibility', 'workspace'), ('workspace_id__isnull', False)), _connector='OR'), name='scenarios_visibility_ws_ck'), models.UniqueConstraint(condition=models.Q(('workspace_id__isnull', True)), fields=('slug',), name='scenarios_global_slug_uq'), models.UniqueConstraint(condition=models.Q(('workspace_id__isnull', False)), fields=('workspace_id', 'slug'), name='scenarios_ws_slug_uq')],
            },
        ),
        migrations.CreateModel(
            name='ManifestVersion',
            fields=[
                ('id', models.UUIDField(default=catalog.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('version', models.TextField()),
                ('manifest', models.JSONField()),
                ('manifest_sha256', models.TextField()),
                ('builtin', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft')),
                ('validation_report', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('scenario', models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='definitions', to='catalog.scenario')),
            ],
            options={
                'db_table': 'scenario_definitions',
            },
        ),
        migrations.CreateModel(
            name='ScenarioInstance',
            fields=[
                ('id', models.UUIDField(default=catalog.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('overrides', models.JSONField(default=dict)),
                ('config_version', models.IntegerField(default=1)),
                ('default_seed', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(db_column='scenario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='instances', to='catalog.scenario')),
                ('scenario_definition', models.ForeignKey(db_column='scenario_definition_id', on_delete=django.db.models.deletion.RESTRICT, related_name='instances', to='catalog.manifestversion')),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, related_name='scenario_instances', to='tenancy.workspace')),
            ],
            options={
                'db_table': 'workspace_scenario_configs',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='manifestversion',
            index=models.Index(fields=['scenario', 'status'], name='scenario_defs_scenario_ix'),
        ),
        migrations.AddConstraint(
            model_name='manifestversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'published', 'deprecated'))), name='scenario_defs_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='manifestversion',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_at__isnull', False), _connector='OR'), name='scenario_defs_published_ck'),
        ),
        migrations.AddConstraint(
            model_name='manifestversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'version'), name='scenario_defs_version_uq'),
        ),
        migrations.AddIndex(
            model_name='scenarioinstance',
            index=models.Index(fields=['workspace'], name='ws_scenario_configs_ws_ix'),
        ),
        migrations.AddConstraint(
            model_name='scenarioinstance',
            constraint=models.CheckConstraint(condition=models.Q(('default_seed__gte', 0), ('default_seed__isnull', True), _connector='OR'), name='ws_scenario_configs_seed_ck'),
        ),
        migrations.AddConstraint(
            model_name='scenarioinstance',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='ws_scenario_configs_name_uq'),
        ),
        # --- §4.1/§4.2 regex CHECKs (Postgres ~; no-op on SQLite). Applied as raw
        # DDL only — not mirrored into model state (the regex CHECK is a DB-only
        # backstop; the manifest grammar + catalog.application enforce the same
        # patterns in Python, so the model carries no matching constraint and the
        # autodetector must not try to add/remove one). ---
        PostgresOnlyRunSQL(sql=_SLUG_CHECK, reverse_sql=_SLUG_CHECK_DROP),
        PostgresOnlyRunSQL(sql=_SEMVER_CHECK, reverse_sql=_SEMVER_CHECK_DROP),
        # --- Layer 2 RLS (database-schema §9.5; M-6 ships RLS with the table) ---
        # Hybrid Class H for the catalog tables (global rows world-readable);
        # standard Class T for the instance table (tenancy marker op so the
        # check_tenancy guard recognizes it). No-op on SQLite.
        EnableHybridRowLevelSecurity(table='scenarios', model_label='catalog.Scenario'),
        EnableHybridRowLevelSecurity(table='scenario_definitions', model_label='catalog.ManifestVersion'),
        EnableRowLevelSecurity(table='workspace_scenario_configs', policy_class='T', model_label='catalog.ScenarioInstance'),
        # --- §4.2 immutability trigger on scenario_definitions (INV-CAT-1). ---
        InstallManifestImmutability(),
    ]
