/* eslint-disable */
/**
 * GENERATED — DO NOT EDIT (frontend-architecture §2.2 IMP-5, §5.1).
 * Source of truth: backend/schema/openapi.yaml. Regenerate with `npm run gen:api`.
 * The CI drift gate (`npm run gen:api:check`) fails on any FE/BE schema drift (ADR-0014).
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/key-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /auth/key-info — the data-plane API-key probe (phase-doc §27).
     *
     *     API-key-only: a JWT here is the wrong credential type for this surface, so we
     *     list only ``ApiKeyAuthentication``. No key (or a JWT) → 401 ``invalid-api-key``
     *     (the key surface's WWW-Authenticate). A revoked key → 401 within 1 s
     *     (SEC-KEY-5), which is exactly what the demo's stopwatch step asserts.
     */
    get: operations['auth_key_info_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_login_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_logout_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_password_reset_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password-reset/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_password_reset_confirm_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_refresh_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/resend-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_resend_verification_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description POST /auth/signup — create unverified account, send verification (§4.1). */
    post: operations['auth_signup_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['auth_verify_email_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/datasets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST /datasets (api-spec §4.10 #57-58). */
    get: operations['datasets_list'];
    put?: never;
    /** @description GET/POST /datasets (api-spec §4.10 #57-58). */
    post: operations['datasets_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/datasets/{dataset_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/DELETE /datasets/{dataset_id} (api-spec §4.10 #59, #61). */
    get: operations['datasets_retrieve'];
    put?: never;
    post?: never;
    /** @description GET/DELETE /datasets/{dataset_id} (api-spec §4.10 #59, #61). */
    delete: operations['datasets_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/datasets/{dataset_id}/download': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /datasets/{dataset_id}/download (api-spec §4.10.3 #60). */
    get: operations['datasets_download'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST /scenarios (api-spec §4.6 #26, #31). */
    get: operations['scenarios_list'];
    put?: never;
    /** @description GET/POST /scenarios (api-spec §4.6 #26, #31). */
    post: operations['scenarios_create_draft'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios/{scenario_slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /scenarios/{scenario_slug} (api-spec §4.6 #27). */
    get: operations['scenarios_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios/{scenario_slug}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /scenarios/{scenario_slug}/versions (api-spec §4.6 #28). */
    get: operations['scenarios_versions_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios/{scenario_slug}/versions/{manifest_version}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /scenarios/{scenario_slug}/versions/{manifest_version} (api-spec §4.6 #29). */
    get: operations['scenarios_version_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios/{scenario_slug}/versions/{manifest_version}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description POST …/versions/{manifest_version}/publish (api-spec §4.6 #32).
     *
     *     JWT, admin of the owning workspace. Requires the persisted ValidationReport
     *     passed (INV-CAT-2); derives + registers v1 schemas transactionally (R-DER).
     *     Unpassed validation → 409 ``conflict``; a non-additive derived schema (only on
     *     a re-publish minor version) → 422 with MAN-V501 errors.
     */
    post: operations['scenarios_version_publish'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/scenarios/{scenario_slug}/versions/{manifest_version}/validation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET …/versions/{manifest_version}/validation (api-spec §4.6 #30).
     *
     *     JWT-only (the L3 dry-run polling target). Returns the persisted §8.3
     *     ValidationReport; L3 dry-run lands in Phase 4, so the report's ``dry_run``
     *     member is ``null`` for L1+L2-only versions.
     */
    get: operations['scenarios_version_validation'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/schemas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /schemas (api-spec §4.12 #62). */
    get: operations['schemas_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/schemas/{subject}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /schemas/{subject} (api-spec §4.12 #63). */
    get: operations['schemas_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/schemas/{subject}/diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /schemas/{subject}/diff?from=a&to=b (api-spec §4.12 #66).
     *
     *     The computed added-fields diff between two registered versions (§5.3): ``added``
     *     is ``properties(to) \ properties(from)`` recursively (incl. fields added inside
     *     an existing nested object), each ``{path, type, required:false}``. Under
     *     ``BACKWARD_ADDITIVE`` ``removed``/``changed`` are empty by construction
     *     (INV-REG-3); they exist in the shape for V-2. ``404`` if either version is
     *     absent; ``400`` ``validation-error`` if ``from ≥ to`` (a diff is forward-only).
     *     The diff is computed, never stored (§3.2). Auth is ``schemas:read`` (A-4).
     */
    get: operations['schemas_diff_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/schemas/{subject}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /schemas/{subject}/versions (api-spec §4.12 #64). */
    get: operations['schemas_versions_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/schemas/{subject}/versions/{schema_version}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /schemas/{subject}/versions/{version} (api-spec §4.12 #65).
     *
     *     ``{version}`` is an integer or the literal ``latest``. The ``schema`` member is
     *     the stored document verbatim (annotations included) — what consumer pipelines
     *     fetch to resolve a ``schema_ref`` (exercise E5).
     */
    get: operations['schemas_version_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST /streams (api-spec §4.8 #39-40). */
    get: operations['streams_list'];
    put?: never;
    /** @description GET/POST /streams (api-spec §4.8 #39-40). */
    post: operations['streams_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET | PATCH /streams/{stream_id} (api-spec §4.8 #41, §4.8.2 #47).
     *
     *     A flat single-resource route (W-2): the workspace is resolved from the resource.
     *     The scoped manager masks a foreign stream to no-row → 404 — but the context must
     *     be armed first. We resolve the stream's workspace via the unscoped manager by its
     *     unique id, then verify the caller may see that workspace (foreign → 404), arm it,
     *     and re-read through the scoped manager.
     *
     *     ``PATCH`` is the live mutation surface (§4.8.2): ``name``/``target_tps`` only
     *     (PIN-3). ``target_tps`` is bounded 1..1,000 (out of range → 400) and quota-capped
     *     at command time (above the plan per-stream cap → 403, INV-TEN-5); the runner picks
     *     it up within 2 s. Any other body key names a pinned field (PIN-4) → 400
     *     validation-error with ``errors[0].code = "immutable_field"``.
     */
    get: operations['streams_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * @description GET | PATCH /streams/{stream_id} (api-spec §4.8 #41, §4.8.2 #47).
     *
     *     A flat single-resource route (W-2): the workspace is resolved from the resource.
     *     The scoped manager masks a foreign stream to no-row → 404 — but the context must
     *     be armed first. We resolve the stream's workspace via the unscoped manager by its
     *     unique id, then verify the caller may see that workspace (foreign → 404), arm it,
     *     and re-read through the scoped manager.
     *
     *     ``PATCH`` is the live mutation surface (§4.8.2): ``name``/``target_tps`` only
     *     (PIN-3). ``target_tps`` is bounded 1..1,000 (out of range → 400) and quota-capped
     *     at command time (above the plan per-stream cap → 403, INV-TEN-5); the runner picks
     *     it up within 2 s. Any other body key names a pinned field (PIN-4) → 400
     *     validation-error with ``errors[0].code = "immutable_field"``.
     */
    patch: operations['streams_patch'];
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/answer-key/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /streams/{id}/answer-key/export (JSONL export of injection records).
     *
     *     Streams the filtered ``chaos_injections`` records as JSONL
     *     (``application/x-ndjson``), one flattened record per line, newest-first — the bulk
     *     counterpart of the paginated injections list for offline grading. Same auth, same
     *     audit (``chaos.answer_key.accessed``) as the other answer-key reads.
     */
    get: operations['streams_answer_key_export'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/answer-key/injections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /streams/{id}/answer-key/injections (api-spec §4.13; chaos-engine §7.3). */
    get: operations['streams_answer_key_injections'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/answer-key/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /streams/{id}/answer-key/summary (api-spec §4.13; chaos-engine §7.3). */
    get: operations['streams_answer_key_summary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/chaos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET | PATCH /streams/{stream_id}/chaos (api-spec §4.8.3; chaos-engine §3.5). */
    get: operations['streams_chaos_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description GET | PATCH /streams/{stream_id}/chaos (api-spec §4.8.3; chaos-engine §3.5). */
    patch: operations['streams_chaos_patch'];
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Pull a page of delivered events by opaque cursor. **Ordering is per `partition_key`**: all events for one partition entity (an actor and its CDC) are delivered in a stable, replay-consistent order. For a multi-shard stream actors are partitioned to disjoint shards by a stable hash of their key, so one actor's events always come from one shard; **cross-shard interleaving is unordered** — there is no global total order over a stream. `shard_count` is pinned at stream start and immutable. */
    get: operations['streams_events'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description POST /streams/{stream_id}/pause (api-spec §4.8.1 #45; T5).
     *
     *     Idempotent (INV-STR-3): pause on a paused-desired stream is a no-op returning
     *     current state. Guarded: pause is legal only from a live lifecycle
     *     (``running``/``starting``/``resuming``) — else 409 invalid-state-transition (T5).
     *     Always an explicit user pause here (``status_reason = user``); the quota/idle
     *     system-pause TRIGGERS are Phase 11 (the lifecycle Celery handler calls
     *     ``request_pause(reason=...)`` directly, not this route).
     */
    post: operations['streams_pause'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description POST /streams/{stream_id}/resume (api-spec §4.8.1 #46; T7).
     *
     *     Idempotent (INV-STR-3): resume on a running-desired stream is a no-op. Guarded:
     *     resume is legal only from ``paused``/``pausing`` — else 409. If the pause reason
     *     was ``quota`` (Phase 11), restored headroom is required at command time
     *     (INV-TEN-5) → else 403 quota-exceeded (T7).
     */
    post: operations['streams_resume'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/schema-upgrades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description POST | GET /streams/{stream_id}/schema-upgrades (api-spec §4.8.4 #50-51).
     *
     *     POST schedules a mid-stream additive evolution (REG-U001..U007 validation →
     *     409 ``conflict`` with the ``errors[]`` extension on failure); ``streams:write``.
     *     Idempotency-Key (I-1): a repeat with the same key returns the already-scheduled
     *     entry (still 201, no duplicate). GET lists every entry
     *     (``scheduled``/``applied``/``cancelled``, the cancelled retained); ``streams:read``.
     */
    get: operations['streams_schema_upgrades_list'];
    put?: never;
    /**
     * @description POST | GET /streams/{stream_id}/schema-upgrades (api-spec §4.8.4 #50-51).
     *
     *     POST schedules a mid-stream additive evolution (REG-U001..U007 validation →
     *     409 ``conflict`` with the ``errors[]`` extension on failure); ``streams:write``.
     *     Idempotency-Key (I-1): a repeat with the same key returns the already-scheduled
     *     entry (still 201, no duplicate). GET lists every entry
     *     (``scheduled``/``applied``/``cancelled``, the cancelled retained); ``streams:read``.
     */
    post: operations['streams_schema_upgrades_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/schema-upgrades/{upgrade_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * @description DELETE /streams/{stream_id}/schema-upgrades/{upgrade_id} (api-spec §4.8.4 #52).
     *
     *     Cancels a ``scheduled`` entry (→ 204); a non-``scheduled`` entry → 409
     *     ``invalid-state-transition``; an unknown id → 404. The cancelled entry is retained
     *     in the list (irreversible history is the audit posture, §10.3). ``streams:write``.
     */
    delete: operations['streams_schema_upgrades_cancel'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/schema-versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /streams/{stream_id}/schema-versions (schema-registry §10.2; #?).
     *
     *     The per-stream effective schema-version projection ``{effective, pending,
     *     applied}``: ``effective`` the §10.2 ``max(materialized pin, highest applied
     *     upgrade target)`` map per subject (the materialized pin lives in the checkpoint
     *     after first start; a preview from the pinned manifest before it); ``pending`` the
     *     ``scheduled`` upgrade entries awaiting their simulated-time cutover; ``applied``
     *     the applied entries (with ``applied_at_wall``/``applied_sequence_no``). Cancelled
     *     entries are surfaced only on the upgrade-list endpoint. ``streams:read``; a
     *     foreign-workspace credential masks to 404 (W-1/W-3) via the shared resolver.
     */
    get: operations['streams_schema_versions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description POST /streams/{stream_id}/start (api-spec §4.8.1 #43; T2/T12/T13). */
    post: operations['streams_start'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /streams/{stream_id}/stats (api-spec §4.11.1 #55; T-none, Phase 6).
     *
     *     The tenant-facing StreamStats read: Redis-resident, rebuildable counters
     *     (``total_events``, ``observed_tps``, ``by_event_type``, ``last_event_at``) with
     *     staleness ≤ 5 s (INV-OBS-2), workspace-scoped (INV-OBS-3). JWT or API-key
     *     (``streams:read``); a foreign-workspace credential masks to 404 (W-1/W-3) via the
     *     shared resolver. ``health`` is derived from the runner lease (heartbeat-fresh
     *     ≤ 15 s) + the counters' age (§4.11.1).
     */
    get: operations['streams_stats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/streams/{stream_id}/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description POST /streams/{stream_id}/stop (api-spec §4.8.1 #44; T9/T10). */
    post: operations['streams_stop'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET/PATCH /users/me and POST /users/me/password / DELETE /users/me (§4.2).
     *
     *     Memberships are injected by the Tenancy app, which subclasses or wraps this
     *     view to populate the `memberships` array; Identity returns the account core.
     */
    get: operations['users_me_retrieve'];
    put?: never;
    post?: never;
    /**
     * @description GET/PATCH /users/me and POST /users/me/password / DELETE /users/me (§4.2).
     *
     *     Memberships are injected by the Tenancy app, which subclasses or wraps this
     *     view to populate the `memberships` array; Identity returns the account core.
     */
    delete: operations['users_me_destroy'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/me/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['users_me_password_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST /workspaces (api-spec §4.3, #12-13). */
    get: operations['workspaces_list'];
    put?: never;
    /** @description GET/POST /workspaces (api-spec §4.3, #12-13). */
    post: operations['workspaces_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/PATCH/DELETE /workspaces/{id} (api-spec §4.3, #14-16). */
    get: operations['workspaces_retrieve'];
    put?: never;
    post?: never;
    /** @description GET/PATCH/DELETE /workspaces/{id} (api-spec §4.3, #14-16). */
    delete: operations['workspaces_delete'];
    options?: never;
    head?: never;
    /** @description GET/PATCH/DELETE /workspaces/{id} (api-spec §4.3, #14-16). */
    patch: operations['workspaces_update'];
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description POST/GET /workspaces/{id}/api-keys (api-spec §4.5, #22-23). */
    get: operations['api_keys_list'];
    put?: never;
    /** @description POST/GET /workspaces/{id}/api-keys (api-spec §4.5, #22-23). */
    post: operations['api_keys_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/api-keys/{api_key_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description DELETE /workspaces/{id}/api-keys/{api_key_id} — revoke (api-spec §4.5, #24). */
    delete: operations['api_keys_revoke'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/audit-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET /workspaces/{id}/audit-log — admin only (api-spec §4.14). */
    get: operations['workspaces_audit_log_list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST /workspaces/{id}/members (api-spec §4.3, #17-18). */
    get: operations['members_list'];
    put?: never;
    /** @description GET/POST /workspaces/{id}/members (api-spec §4.3, #17-18). */
    post: operations['members_add'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/members/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description PATCH/DELETE /workspaces/{id}/members/{user_id} (api-spec §4.3, #19-20). */
    delete: operations['members_remove'];
    options?: never;
    head?: never;
    /** @description PATCH/DELETE /workspaces/{id}/members/{user_id} (api-spec §4.3, #19-20). */
    patch: operations['members_update'];
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/quotas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description GET /workspaces/{id}/quotas (api-spec §4.4). JWT | Key(streams:read).
     *
     *     ApiKey auth listed first so both-headers → 400 ambiguous-credentials (A-2).
     */
    get: operations['workspaces_quotas_retrieve'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/scenario-instances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/POST …/scenario-instances (api-spec §4.7 #33-34). */
    get: operations['scenario_instances_list'];
    put?: never;
    /** @description GET/POST …/scenario-instances (api-spec §4.7 #33-34). */
    post: operations['scenario_instances_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/scenario-instances/{scenario_instance_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/DELETE …/scenario-instances/{id} (api-spec §4.7 #35, #38). */
    get: operations['scenario_instances_retrieve'];
    put?: never;
    post?: never;
    /** @description GET/DELETE …/scenario-instances/{id} (api-spec §4.7 #35, #38). */
    delete: operations['scenario_instances_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/workspaces/{workspace_id}/scenario-instances/{scenario_instance_id}/configuration': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description GET/PUT …/scenario-instances/{id}/configuration (api-spec §4.7 #36-37). */
    get: operations['scenario_instances_configuration_retrieve'];
    /** @description GET/PUT …/scenario-instances/{id}/configuration (api-spec §4.7 #36-37). */
    put: operations['scenario_instances_configuration_replace'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description One added property in the computed diff (#66). */
    AddedField: {
      path: string;
      type: string;
      required: boolean;
    };
    /**
     * @description One flattened InjectionRecord on the wire (api-spec §4.13 / event-model §7.3).
     *
     *     Common fields are typed; mode-specific members (``copies``, ``delay_simulated_ms``,
     *     ``mutations``, …) are flattened from ``details`` and pass through as extra keys —
     *     this serializer documents the stable common shape, the view emits the full record.
     */
    AnswerKeyInjection: {
      /** Format: uuid */
      injection_id: string;
      mode: string;
      /** Format: uuid */
      stream_id: string;
      shard_id: number;
      /** Format: uuid */
      event_id: string;
      sequence_no: number;
      /** Format: date-time */
      occurred_at: string;
      /** Format: date-time */
      canonical_emitted_at: string;
      /** Format: date-time */
      recorded_at: string;
    };
    AnswerKeyInjectionsPage: {
      data: components['schemas']['AnswerKeyInjection'][];
      next_cursor: string | null;
    };
    /** @description The per-mode answer-key count aggregate (api-spec §4.13 summary). */
    AnswerKeySummary: {
      /** Format: uuid */
      stream_id: string;
      window: components['schemas']['_AnswerKeyWindow'];
      by_mode: {
        [key: string]: unknown;
      };
      total_injections: number;
      /** Format: date-time */
      as_of: string;
    };
    ApiKeyCreate: {
      name: string;
      scopes: components['schemas']['ScopesEnum'][];
      /** Format: date-time */
      expires_at?: string | null;
    };
    /** @description The reveal-once 201 — the ONLY response carrying the plaintext ``key``. */
    ApiKeyCreated: {
      /** Format: uuid */
      api_key_id: string;
      /** Format: uuid */
      workspace_id: string;
      name: string;
      key: string;
      prefix: string;
      last4: string;
      scopes: string[];
      state: string;
      /** Format: date-time */
      expires_at: string | null;
      /** Format: uuid */
      created_by: string;
      /** Format: date-time */
      created_at: string;
    };
    /** @description List item — never carries ``key`` (api-spec §4.5). */
    ApiKeyListItem: {
      /** Format: uuid */
      api_key_id: string;
      name: string;
      prefix: string;
      last4: string;
      scopes: string[];
      state: string;
      /** Format: date-time */
      last_used_at: string | null;
      /** Format: date-time */
      expires_at: string | null;
      /** Format: uuid */
      created_by: string;
      /** Format: date-time */
      created_at: string;
    };
    ApiKeyPage: {
      data: components['schemas']['ApiKeyListItem'][];
      next_cursor: string | null;
    };
    AuditEntry: {
      audit_id: string;
      /** Format: date-time */
      occurred_at: string;
      actor: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      workspace_id: string | null;
      action: string;
      target: {
        [key: string]: unknown;
      };
      metadata: {
        [key: string]: unknown;
      };
      request_id?: string | null;
    };
    AuditEntryPage: {
      data: components['schemas']['AuditEntry'][];
      next_cursor: string | null;
    };
    ChangePasswordRequest: {
      current_password: string;
      new_password: string;
      refresh_token?: string;
    };
    /** @description The live ChaosPolicy resource (api-spec §4.8.3 GET/PATCH 200). */
    ChaosPolicyResponse: {
      /** Format: uuid */
      stream_id: string;
      modes: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      updated_at: string;
    };
    /**
     * @description * `gzip` - gzip
     *     * `none` - none
     * @enum {string}
     */
    CompressionEnum: 'gzip' | 'none';
    /** @description ``GET/PUT …/configuration`` (#36/#37) — the overlay + its revision. */
    Configuration: {
      config_revision: number;
      configuration: {
        [key: string]: unknown;
      };
    };
    ConfigurationReplace: {
      configuration: {
        [key: string]: unknown;
      };
    };
    /** @description The dataset resource (api-spec §4.10.2). */
    Dataset: {
      /** Format: uuid */
      dataset_id: string;
      /** Format: uuid */
      workspace_id: string;
      /** Format: uuid */
      scenario_instance_id: string;
      name: string;
      status: string;
      /** Format: double */
      progress: number;
      seed: string;
      pin_sha256: string;
      simulated_window: {
        [key: string]: unknown;
      };
      estimated_events: number;
      event_count: number | null;
      size_bytes: number | null;
      compression: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      ready_at: string | null;
      /** Format: date-time */
      expires_at: string | null;
      failure_reason: string;
      download_path: string;
    };
    /** @description ``POST /datasets`` request body (api-spec §4.10.1). */
    DatasetCreate: {
      /** Format: uuid */
      workspace_id: string;
      /** Format: uuid */
      scenario_instance_id: string;
      name: string;
      seed?: string | null;
      simulated_days: number;
      /** Format: date-time */
      virtual_epoch?: string | null;
      /** @default gzip */
      compression: components['schemas']['CompressionEnum'];
      chaos?: {
        [key: string]: unknown;
      };
    };
    DetailResponse: {
      detail: string;
    };
    /** @description ``POST /scenarios`` — create a workspace-visibility draft (§12 AI seam). */
    DraftCreate: {
      /** Format: uuid */
      workspace_id: string;
      document: {
        [key: string]: unknown;
      };
    };
    /** @description resend-verification / password-reset request body. */
    EmailOnlyRequest: {
      /** Format: email */
      email: string;
      captcha_token?: string;
    };
    /**
     * @description The ``{data, next_cursor}`` page envelope (api-spec §2.6; §5.1).
     *
     *     Documentation/response shape only — the viewset builds the dict directly from the
     *     service's :class:`~delivery.application.services.EventsPage` (the envelopes are
     *     already delivered-shape, so no per-field serialization re-touches them).
     *     ``next_cursor`` is never null on this endpoint (RC-2).
     */
    EventsPage: {
      data: {
        [key: string]: unknown;
      }[];
      next_cursor: string;
    };
    /**
     * @description * `healthy` - healthy
     *     * `degraded` - degraded
     *     * `stale` - stale
     * @enum {string}
     */
    HealthEnum: 'healthy' | 'degraded' | 'stale';
    InstanceCreate: {
      name: string;
      scenario_slug: string;
      manifest_version: string;
      configuration?: {
        [key: string]: unknown;
      };
      default_seed?: number | null;
    };
    /** @description The ``GET /auth/key-info`` introspection body (phase doc §27). */
    KeyInfo: {
      /** Format: uuid */
      api_key_id: string;
      /** Format: uuid */
      workspace_id: string;
      prefix: string;
      scopes: string[];
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LogoutRequest: {
      refresh_token?: string;
    };
    ManifestVersionDetail: {
      scenario_slug: string;
      manifest_version: string;
      status: string;
      sha256: string;
      /** Format: date-time */
      published_at: string | null;
      document: {
        [key: string]: unknown;
      };
    };
    MemberAdd: {
      /** Format: email */
      email: string;
      /** @default member */
      role: components['schemas']['RoleEnum'];
    };
    Membership: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      role: string;
      /** Format: date-time */
      joined_at: string;
    };
    MembershipPage: {
      data: components['schemas']['Membership'][];
      next_cursor: string | null;
    };
    MembershipSummary: {
      /** Format: uuid */
      workspace_id: string;
      name: string;
      slug: string;
      role: string;
    };
    /** @enum {unknown} */
    NullEnum: null;
    PasswordResetConfirmRequest: {
      token: string;
      new_password: string;
    };
    PatchedMemberRole: {
      role?: components['schemas']['RoleEnum'];
    };
    /**
     * @description ``PATCH /streams/{id}`` body (api-spec §4.8.2; RFC 7386 merge-patch).
     *
     *     Mutable fields: ``name`` and ``target_tps`` (PIN-3). ``target_tps`` is bounded
     *     1..1,000 (out of range → 400 ``validation-error``); the plan per-stream cap is a
     *     separate 403 ``quota-exceeded`` check at command time (INV-TEN-5). Everything else
     *     on the stream is pinned (PIN-4) — patching an immutable field is rejected with a
     *     ``validation-error`` whose ``errors[0].code = "immutable_field"`` (handled in the
     *     view, which masks unknown/pinned keys before serializer validation).
     */
    PatchedStreamPatch: {
      name?: string;
      target_tps?: number;
    };
    PatchedWorkspaceRename: {
      name?: string;
    };
    Quota: {
      /** Format: uuid */
      workspace_id: string;
      plan: string;
      quotas: {
        [key: string]: unknown;
      };
    };
    RefreshRequest: {
      refresh_token?: string;
    };
    /**
     * @description * `admin` - Admin
     *     * `member` - Member
     * @enum {string}
     */
    RoleEnum: 'admin' | 'member';
    ScenarioDetail: {
      scenario_slug: string;
      title: string;
      description: string;
      visibility: string;
      latest_version: string | null;
      published_versions: string[];
      /** Format: date-time */
      created_at: string;
      versions: components['schemas']['VersionSummary'][];
    };
    ScenarioInstance: {
      /** Format: uuid */
      scenario_instance_id: string;
      /** Format: uuid */
      workspace_id: string;
      name: string;
      scenario_slug: string;
      manifest_version: string;
      config_revision: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    ScenarioInstancePage: {
      data: components['schemas']['ScenarioInstance'][];
      next_cursor: string | null;
    };
    ScenarioPage: {
      data: components['schemas']['ScenarioSummary'][];
      next_cursor: string | null;
    };
    ScenarioSummary: {
      scenario_slug: string;
      title: string;
      description: string;
      visibility: string;
      latest_version: string | null;
      published_versions: string[];
      /** Format: date-time */
      created_at: string;
    };
    /**
     * @description The computed version-to-version diff (#66).
     *
     *     Under ``BACKWARD_ADDITIVE`` (the only MVP mode) ``removed_fields`` /
     *     ``changed_fields`` are always empty by construction (INV-REG-3); they are in the
     *     shape so the contract survives a future compatibility-mode addition (V-2).
     */
    SchemaDiff: {
      subject: string;
      from_version: number;
      to_version: number;
      added_fields: components['schemas']['AddedField'][];
      removed_fields: components['schemas']['AddedField'][];
      changed_fields: components['schemas']['AddedField'][];
    };
    SchemaSubjectPage: {
      data: components['schemas']['SubjectSummary'][];
      next_cursor: string | null;
    };
    /**
     * @description ``POST /streams/{id}/schema-upgrades`` body (api-spec §4.8.4 / schema-registry §10.3).
     *
     *     ``subject`` is the dotted subject name; ``target_version`` the registered version
     *     to evolve to (≥ 1). ``at`` is the SIMULATED-time cutover instant (``occurred_at``
     *     domain) — optional; omitted means "the next tick boundary" (effectively
     *     immediately). The REG-U001..U007 semantic checks run in the service against the
     *     stream's pinned manifest + virtual clock (this serializer only shapes the wire).
     */
    SchemaUpgradeCreate: {
      subject: string;
      target_version: number;
      /** Format: date-time */
      at?: string | null;
    };
    /**
     * @description The schema-upgrade resource on the wire (api-spec §4.8.4 #50-52).
     *
     *     The ``scheduled`` 201 carries ``upgrade_id``/``status``/``created_at``; ``applied``
     *     entries additionally carry ``applied_at_wall`` and the per-shard
     *     ``applied_sequence_no`` written by the runner cutover (§10.4); ``cancelled`` entries
     *     carry ``cancelled_at``. ``at`` is the simulated-time cutover instant (null ⇒ next
     *     tick). The output is assembled from the persisted jsonb entry (the runner and the
     *     cancel path complete the optional members in place).
     */
    SchemaUpgradeResponse: {
      /** Format: uuid */
      upgrade_id: string;
      /** Format: uuid */
      stream_id: string;
      subject: string;
      target_version: number;
      /** Format: date-time */
      at: string | null;
      status: components['schemas']['StatusEnum'];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      applied_at_wall?: string | null;
      applied_sequence_no?: number | null;
      /** Format: date-time */
      cancelled_at?: string | null;
    };
    SchemaVersionPage: {
      data: components['schemas']['VersionProvenance'][];
      next_cursor: string | null;
    };
    /**
     * @description * `events:read` - events:read
     *     * `streams:read` - streams:read
     *     * `streams:write` - streams:write
     *     * `schemas:read` - schemas:read
     *     * `answer_key:read` - answer_key:read
     * @enum {string}
     */
    ScopesEnum:
      | 'events:read'
      | 'streams:read'
      | 'streams:write'
      | 'schemas:read'
      | 'answer_key:read';
    SignupRequest: {
      /** Format: email */
      email: string;
      password: string;
      captcha_token?: string;
    };
    SignupResponse: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      is_verified: boolean;
      /** Format: date-time */
      created_at: string;
    };
    /**
     * @description * `scheduled` - scheduled
     *     * `applied` - applied
     *     * `cancelled` - cancelled
     * @enum {string}
     */
    StatusEnum: 'scheduled' | 'applied' | 'cancelled';
    /**
     * @description ``POST /streams`` body (api-spec §4.8).
     *
     *     ``seed`` is optional (server-generated when omitted) and accepted as a string or
     *     integer in [0, 2**63-1]. ``target_tps`` defaults to 10, bounded 1..1000 (the v1
     *     request bound; the plan cap is a separate 403 quota check at command time).
     *     ``chaos`` is the optional initial policy. v1 runs ``live`` mode only (backfill is
     *     the datasets resource), so ``clock_mode`` is fixed to ``live`` here.
     */
    StreamCreate: {
      /** Format: uuid */
      workspace_id: string;
      /** Format: uuid */
      scenario_instance_id: string;
      name: string;
      seed?: string | null;
      /** @default 10 */
      target_tps: number;
      /** @default 1 */
      shard_count: number;
      chaos?: {
        [key: string]: unknown;
      };
      schema_version_pins?: {
        [key: string]: number;
      };
      virtual_clock?: components['schemas']['VirtualClockInput'];
    };
    StreamPage: {
      data: components['schemas']['StreamResponse'][];
      next_cursor: string | null;
    };
    /**
     * @description The Stream resource on the wire (api-spec §4.8). Read-only output shape.
     *
     *     ``status`` is the surfaced lifecycle string (``running``, ``paused_quota``, …);
     *     ``status_reason`` is the raw reason. ``seed`` and ``pin_sha256`` are the
     *     determinism fingerprint surfaced read-only (INV-STR-5).
     */
    StreamResponse: {
      /** Format: uuid */
      stream_id: string;
      /** Format: uuid */
      workspace_id: string;
      /** Format: uuid */
      scenario_instance_id: string;
      name: string;
      scenario_slug: string;
      manifest_version: string;
      config_revision: number;
      pin_sha256: string;
      seed: string;
      status: string;
      status_reason: string;
      desired_state: components['schemas']['_DesiredState'];
      virtual_clock: components['schemas']['_VirtualClock'];
      schema_versions: {
        [key: string]: number;
      };
      shard_count: number;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      started_at: string | null;
      /** Format: date-time */
      last_transition_at: string | null;
    };
    StreamSchemaUpgradePage: {
      data: components['schemas']['SchemaUpgradeResponse'][];
      next_cursor: string | null;
    };
    /**
     * @description ``GET /streams/{id}/schema-versions`` → ``{effective, pending, applied}`` (§10.2).
     *
     *     ``effective`` is the per-subject effective-version map
     *     (``effective = max(materialized pin, highest applied upgrade target)``); ``{}``
     *     before first start. ``pending`` is the ``scheduled`` upgrade entries (awaiting
     *     their simulated-time cutover); ``applied`` the ``applied`` entries (each carrying
     *     ``applied_at_wall`` + ``applied_sequence_no``). Cancelled entries are history,
     *     surfaced only on the upgrade-list endpoint, not here.
     */
    StreamSchemaVersionsResponse: {
      effective: {
        [key: string]: number;
      };
      pending: components['schemas']['SchemaUpgradeResponse'][];
      applied: components['schemas']['SchemaUpgradeResponse'][];
    };
    /**
     * @description The ``GET /streams/{id}/stats`` response (api-spec §4.11.1, Phase 6).
     *
     *     Redis-resident, rebuildable counters (INV-OBS-2): ``total_events``,
     *     ``observed_tps`` (10 s sliding window), ``by_event_type``, ``last_event_at``.
     *     ``health`` is the closed enum (``healthy``/``degraded``/``stale``), ``null`` for a
     *     non-live stream. The shape is assembled by the delivery stats service; this
     *     serializer is the OpenAPI/output contract.
     */
    StreamStatsResponse: {
      /** Format: uuid */
      stream_id: string;
      status: string;
      health: (components['schemas']['HealthEnum'] | components['schemas']['NullEnum']) | null;
      total_events: number;
      /** Format: double */
      observed_tps: number;
      target_tps: number;
      /** Format: date-time */
      last_event_at: string | null;
      by_event_type: {
        [key: string]: number;
      };
      buffer: components['schemas']['_StatsBuffer'];
      virtual_clock: components['schemas']['_StatsVirtualClock'];
      /** Format: date-time */
      as_of: string;
    };
    /** @description Subject detail (#63): the summary plus created_at + per-version provenance. */
    SubjectDetail: {
      subject: string;
      scenario_slug: string;
      compatibility: string;
      latest_version: number | null;
      versions: number[];
      /** Format: date-time */
      created_at: string;
      version_provenance: components['schemas']['VersionProvenance'][];
    };
    /** @description Subject summary (#62). */
    SubjectSummary: {
      subject: string;
      scenario_slug: string;
      compatibility: string;
      latest_version: number | null;
      versions: number[];
    };
    /**
     * @description Login / refresh body. The refresh token is **never** in the body —
     *     it rides the `df_refresh` HttpOnly cookie (SEC-AUTH-3); only the access
     *     token is returned, held in memory by the SPA (SEC-AUTH-2).
     */
    TokenPairResponse: {
      access_token: string;
      /** @default Bearer */
      token_type: string;
      access_expires_in: number;
      refresh_expires_in: number;
    };
    UserMeResponse: {
      /** Format: uuid */
      user_id: string;
      /** Format: email */
      email: string;
      is_verified: boolean;
      /** Format: date-time */
      created_at: string;
      memberships: components['schemas']['MembershipSummary'][];
    };
    /**
     * @description The §8.3 ValidationReport (#30) — the dry-run polling target.
     *
     *     ``errors``/``warnings`` are wire keys that collide with DRF's own ``Serializer``
     *     attributes; the ``# type: ignore[assignment]`` keeps them declared as fields
     *     (DRF resolves the shadowing at runtime) while documenting the §8.3 shape.
     */
    ValidationReport: {
      status: string;
      schema_version?: string;
      errors?: {
        [key: string]: unknown;
      }[];
      warnings?: {
        [key: string]: unknown;
      }[];
      dry_run?: {
        [key: string]: unknown;
      } | null;
    };
    VerifyEmailRequest: {
      token: string;
    };
    VerifyEmailResponse: {
      /** Format: uuid */
      user_id: string;
      is_verified: boolean;
    };
    VersionPage: {
      data: components['schemas']['VersionSummary'][];
      next_cursor: string | null;
    };
    /** @description One version's provenance row (#63 detail, #64 list). */
    VersionProvenance: {
      version: number;
      /** Format: date-time */
      registered_at: string;
      manifest_version: string | null;
    };
    /** @description One version's full record including the schema document (#65). */
    VersionRecord: {
      subject: string;
      version: number;
      manifest_version: string | null;
      /** Format: date-time */
      registered_at: string;
      schema: {
        [key: string]: unknown;
      };
    };
    VersionSummary: {
      manifest_version: string;
      status: string;
      /** Format: date-time */
      published_at: string | null;
    };
    /** @description The optional virtual-clock block on create (api-spec §4.8 body). */
    VirtualClockInput: {
      /** Format: date-time */
      virtual_epoch?: string;
      /** Format: decimal */
      speed_multiplier?: string;
    };
    Workspace: {
      /** Format: uuid */
      workspace_id: string;
      name: string;
      slug: string;
      plan: string;
      role?: string;
      member_count: number;
      /** Format: date-time */
      created_at: string;
    };
    WorkspaceCreate: {
      name: string;
      slug?: string | null;
    };
    WorkspacePage: {
      data: components['schemas']['Workspace'][];
      next_cursor: string | null;
    };
    _AnswerKeyWindow: {
      /** Format: date-time */
      to: string | null;
      /** Format: date-time */
      from: string | null;
    };
    _DesiredState: {
      run_state: string;
      target_tps: number;
    };
    _StatsBuffer: {
      /** Format: date-time */
      earliest_available_at: string | null;
      /** Format: date-time */
      latest_event_at: string | null;
      retention_hours: number;
    };
    _StatsVirtualClock: {
      /** Format: date-time */
      virtual_now: string | null;
      /** Format: double */
      speed_multiplier: number;
    };
    _VirtualClock: {
      /** Format: date-time */
      virtual_epoch: string;
      /** Format: decimal */
      speed_multiplier: string;
      /** Format: date-time */
      virtual_now?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_key_info_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['KeyInfo'];
        };
      };
    };
  };
  auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
        'application/x-www-form-urlencoded': components['schemas']['LoginRequest'];
        'multipart/form-data': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPairResponse'];
        };
      };
    };
  };
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['LogoutRequest'];
        'application/x-www-form-urlencoded': components['schemas']['LogoutRequest'];
        'multipart/form-data': components['schemas']['LogoutRequest'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_password_reset_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailOnlyRequest'];
        'application/x-www-form-urlencoded': components['schemas']['EmailOnlyRequest'];
        'multipart/form-data': components['schemas']['EmailOnlyRequest'];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailResponse'];
        };
      };
    };
  };
  auth_password_reset_confirm_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirmRequest'];
        'application/x-www-form-urlencoded': components['schemas']['PasswordResetConfirmRequest'];
        'multipart/form-data': components['schemas']['PasswordResetConfirmRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailResponse'];
        };
      };
    };
  };
  auth_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
        'application/x-www-form-urlencoded': components['schemas']['RefreshRequest'];
        'multipart/form-data': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPairResponse'];
        };
      };
    };
  };
  auth_resend_verification_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailOnlyRequest'];
        'application/x-www-form-urlencoded': components['schemas']['EmailOnlyRequest'];
        'multipart/form-data': components['schemas']['EmailOnlyRequest'];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailResponse'];
        };
      };
    };
  };
  auth_signup_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest'];
        'application/x-www-form-urlencoded': components['schemas']['SignupRequest'];
        'multipart/form-data': components['schemas']['SignupRequest'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SignupResponse'];
        };
      };
    };
  };
  auth_verify_email_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyEmailRequest'];
        'application/x-www-form-urlencoded': components['schemas']['VerifyEmailRequest'];
        'multipart/form-data': components['schemas']['VerifyEmailRequest'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifyEmailResponse'];
        };
      };
    };
  };
  datasets_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'][];
        };
      };
    };
  };
  datasets_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DatasetCreate'];
        'application/x-www-form-urlencoded': components['schemas']['DatasetCreate'];
        'multipart/form-data': components['schemas']['DatasetCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'];
        };
      };
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'];
        };
      };
    };
  };
  datasets_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dataset'];
        };
      };
    };
  };
  datasets_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  datasets_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        dataset_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  scenarios_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioPage'];
        };
      };
    };
  };
  scenarios_create_draft: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftCreate'];
        'application/x-www-form-urlencoded': components['schemas']['DraftCreate'];
        'multipart/form-data': components['schemas']['DraftCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManifestVersionDetail'];
        };
      };
    };
  };
  scenarios_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioDetail'];
        };
      };
    };
  };
  scenarios_versions_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionPage'];
        };
      };
    };
  };
  scenarios_version_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        manifest_version: string;
        scenario_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManifestVersionDetail'];
        };
      };
    };
  };
  scenarios_version_publish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        manifest_version: string;
        scenario_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManifestVersionDetail'];
        };
      };
    };
  };
  scenarios_version_validation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        manifest_version: string;
        scenario_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationReport'];
        };
      };
    };
  };
  schemas_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SchemaSubjectPage'];
        };
      };
    };
  };
  schemas_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subject: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubjectDetail'];
        };
      };
    };
  };
  schemas_diff_retrieve: {
    parameters: {
      query: {
        from: number;
        to: number;
      };
      header?: never;
      path: {
        subject: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SchemaDiff'];
        };
      };
    };
  };
  schemas_versions_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subject: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SchemaVersionPage'];
        };
      };
    };
  };
  schemas_version_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schema_version: string;
        subject: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionRecord'];
        };
      };
    };
  };
  streams_list: {
    parameters: {
      query: {
        /** @description Filter to streams of one scenario instance. */
        scenario_instance_id?: string;
        /** @description Comma list of lifecycle_state values to filter by. */
        status?: string;
        /** @description The owning workspace UUID (W-2); absent → 404. */
        workspace_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamPage'];
        };
      };
    };
  };
  streams_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StreamCreate'];
        'application/x-www-form-urlencoded': components['schemas']['StreamCreate'];
        'multipart/form-data': components['schemas']['StreamCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedStreamPatch'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedStreamPatch'];
        'multipart/form-data': components['schemas']['PatchedStreamPatch'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_answer_key_export: {
    parameters: {
      query?: {
        /** @description Exact affected canonical event id. */
        event_id?: string;
        /** @description RFC-3339 lower bound on occurred_at. */
        from?: string;
        /** @description One of the seven ChaosMode identifiers. */
        mode?: string;
        /** @description RFC-3339 upper bound on occurred_at. */
        to?: string;
      };
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  streams_answer_key_injections: {
    parameters: {
      query?: {
        /** @description Opaque resume cursor (P-1). */
        cursor?: string;
        /** @description Exact affected canonical event id. */
        event_id?: string;
        /** @description RFC-3339 lower bound on occurred_at. */
        from?: string;
        /** @description Page size 1..500 (default 100). */
        limit?: number;
        /** @description One of the seven ChaosMode identifiers. */
        mode?: string;
        /** @description RFC-3339 upper bound on occurred_at. */
        to?: string;
      };
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnswerKeyInjectionsPage'];
        };
      };
    };
  };
  streams_answer_key_summary: {
    parameters: {
      query?: {
        /** @description Exact affected canonical event id. */
        event_id?: string;
        /** @description RFC-3339 lower bound on occurred_at. */
        from?: string;
        /** @description One of the seven ChaosMode identifiers. */
        mode?: string;
        /** @description RFC-3339 upper bound on occurred_at. */
        to?: string;
      };
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AnswerKeySummary'];
        };
      };
    };
  };
  streams_chaos_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChaosPolicyResponse'];
        };
      };
    };
  };
  streams_chaos_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChaosPolicyResponse'];
        };
      };
    };
  };
  streams_events: {
    parameters: {
      query?: {
        /** @description Opaque resume cursor (RC-7). */
        cursor?: string;
        /** @description Per-entity CDC filter (R-CDC-7); pair with entity_type. */
        entity_key?: string;
        /** @description Per-entity CDC filter (R-CDC-7); pair with entity_key. */
        entity_type?: string;
        /** @description earliest | latest | RFC-3339 start position. */
        from?: string;
        /** @description Page size 1..1000 (default 100). */
        limit?: number;
        /** @description Comma list, ≤20 event-type filter. */
        types?: string;
      };
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventsPage'];
        };
      };
    };
  };
  streams_pause: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_resume: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_schema_upgrades_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamSchemaUpgradePage'];
        };
      };
    };
  };
  streams_schema_upgrades_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SchemaUpgradeCreate'];
        'application/x-www-form-urlencoded': components['schemas']['SchemaUpgradeCreate'];
        'multipart/form-data': components['schemas']['SchemaUpgradeCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SchemaUpgradeResponse'];
        };
      };
    };
  };
  streams_schema_upgrades_cancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
        upgrade_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  streams_schema_versions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamSchemaVersionsResponse'];
        };
      };
    };
  };
  streams_start: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  streams_stats: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamStatsResponse'];
        };
      };
    };
  };
  streams_stop: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stream_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamResponse'];
        };
      };
    };
  };
  users_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserMeResponse'];
        };
      };
    };
  };
  users_me_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  users_me_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
        'application/x-www-form-urlencoded': components['schemas']['ChangePasswordRequest'];
        'multipart/form-data': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workspaces_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkspacePage'];
        };
      };
    };
  };
  workspaces_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceCreate'];
        'application/x-www-form-urlencoded': components['schemas']['WorkspaceCreate'];
        'multipart/form-data': components['schemas']['WorkspaceCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workspace'];
        };
      };
    };
  };
  workspaces_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workspace'];
        };
      };
    };
  };
  workspaces_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workspaces_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedWorkspaceRename'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedWorkspaceRename'];
        'multipart/form-data': components['schemas']['PatchedWorkspaceRename'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workspace'];
        };
      };
    };
  };
  api_keys_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiKeyPage'];
        };
      };
    };
  };
  api_keys_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ApiKeyCreate'];
        'application/x-www-form-urlencoded': components['schemas']['ApiKeyCreate'];
        'multipart/form-data': components['schemas']['ApiKeyCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiKeyCreated'];
        };
      };
    };
  };
  api_keys_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        api_key_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  workspaces_audit_log_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditEntryPage'];
        };
      };
    };
  };
  members_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MembershipPage'];
        };
      };
    };
  };
  members_add: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberAdd'];
        'application/x-www-form-urlencoded': components['schemas']['MemberAdd'];
        'multipart/form-data': components['schemas']['MemberAdd'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Membership'];
        };
      };
    };
  };
  members_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  members_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedMemberRole'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedMemberRole'];
        'multipart/form-data': components['schemas']['PatchedMemberRole'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Membership'];
        };
      };
    };
  };
  workspaces_quotas_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Quota'];
        };
      };
    };
  };
  scenario_instances_list: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioInstancePage'];
        };
      };
    };
  };
  scenario_instances_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InstanceCreate'];
        'application/x-www-form-urlencoded': components['schemas']['InstanceCreate'];
        'multipart/form-data': components['schemas']['InstanceCreate'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioInstance'];
        };
      };
    };
  };
  scenario_instances_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_instance_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScenarioInstance'];
        };
      };
    };
  };
  scenario_instances_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_instance_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  scenario_instances_configuration_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_instance_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Configuration'];
        };
      };
    };
  };
  scenario_instances_configuration_replace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scenario_instance_id: string;
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfigurationReplace'];
        'application/x-www-form-urlencoded': components['schemas']['ConfigurationReplace'];
        'multipart/form-data': components['schemas']['ConfigurationReplace'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Configuration'];
        };
      };
    };
  };
}
type FlattenedDeepRequired<T> = {
  [K in keyof T]-?: FlattenedDeepRequired<
    T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]
  >;
};
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [unknown[]]
  ? Readonly<Exclude<T, undefined>>
  : Readonly<Exclude<T, undefined>[]>;
export const compressionEnumValues: ReadonlyArray<
  FlattenedDeepRequired<components>['schemas']['CompressionEnum']
> = ['gzip', 'none'];
export const healthEnumValues: ReadonlyArray<
  FlattenedDeepRequired<components>['schemas']['HealthEnum']
> = ['healthy', 'degraded', 'stale'];
export const roleEnumValues: ReadonlyArray<
  FlattenedDeepRequired<components>['schemas']['RoleEnum']
> = ['admin', 'member'];
export const scopesEnumValues: ReadonlyArray<
  FlattenedDeepRequired<components>['schemas']['ScopesEnum']
> = ['events:read', 'streams:read', 'streams:write', 'schemas:read', 'answer_key:read'];
export const statusEnumValues: ReadonlyArray<
  FlattenedDeepRequired<components>['schemas']['StatusEnum']
> = ['scheduled', 'applied', 'cancelled'];
