"""Ledger partition DDL — the time-partitioned parent + daily partitions
(database-schema §5.5, §8.1-8.2; M-5).

``ground_truth_ledger`` is ``PARTITION BY RANGE (emitted_at)`` with daily,
UTC-aligned partitions and **no DEFAULT partition** (a write outside any attached
range is a loud failure — §8.1). Django's ``CreateModel`` cannot emit a
partitioned parent, so the migration calls :func:`create_ledger_parent_sql` (raw
DDL) and the model is registered as state-only. Individual partitions are owned by
the partition manager (M-5), exposed here as :func:`create_partition` /
:func:`drop_partition` and driven by the management commands.

Each new partition gets the §5.5 per-partition index template and the §9.7
RLS enable/force/policy template applied (belt-and-suspenders: direct-to-partition
access would otherwise consult only the partition's own policies).

Pure DDL string builders + a thin executor seam; Postgres-only (the SQLite unit
lane skips partition DDL — RLS/partitioning are Postgres constructs).
"""

from __future__ import annotations

from datetime import UTC, date, datetime, timedelta
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

LEDGER_TABLE = "ground_truth_ledger"

# The §5.5 partition-parent DDL: the full column set, the composite PK including
# the partition key, and PARTITION BY RANGE (emitted_at). Kept here (not the
# migration body) so the partition manager and the migration share one source.
_CREATE_PARENT = f"""
CREATE TABLE IF NOT EXISTS {LEDGER_TABLE} (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_id  uuid NOT NULL,
    stream_id     uuid NOT NULL,
    shard_id      integer NOT NULL,
    sequence_no   bigint NOT NULL,
    event_id      uuid NOT NULL,
    event_type    text NOT NULL,
    occurred_at   timestamptz NOT NULL,
    emitted_at    timestamptz NOT NULL,
    envelope      jsonb NOT NULL,
    PRIMARY KEY (stream_id, shard_id, sequence_no, emitted_at)
) PARTITION BY RANGE (emitted_at);
"""

_DROP_PARENT = f"DROP TABLE IF EXISTS {LEDGER_TABLE} CASCADE;"


def create_ledger_parent_sql() -> str:
    """The CREATE TABLE … PARTITION BY RANGE (emitted_at) parent DDL (§5.5)."""
    return _CREATE_PARENT


def drop_ledger_parent_sql() -> str:
    """Reverse: drop the partitioned parent (and all partitions, CASCADE)."""
    return _DROP_PARENT


def partition_name(day: date) -> str:
    """The §8.1 partition name, e.g. ``ground_truth_ledger_p20260610``."""
    return f"{LEDGER_TABLE}_p{day:%Y%m%d}"


def _bounds(day: date) -> tuple[str, str]:
    """UTC-aligned ``[day 00:00, next day 00:00)`` RANGE bounds (§8.1).

    Returned as *naive* ``YYYY-MM-DD HH:MM:SS`` strings so the partition DDL can
    append the single ``+00`` UTC offset (a tz-aware ``isoformat`` would already
    carry ``+00:00``, yielding the invalid double-offset literal Postgres rejects).
    """
    start = datetime.combine(day, datetime.min.time(), tzinfo=UTC)
    end = start + timedelta(days=1)
    fmt = "%Y-%m-%d %H:%M:%S"
    return start.strftime(fmt), end.strftime(fmt)


def create_partition_sql(day: date) -> list[str]:
    """DDL to create-and-attach one daily partition + its indexes + RLS (§8.2).

    Returns a list of statements (CREATE TABLE … PARTITION OF, the two
    per-partition indexes from the §5.5 template, and the §9.7 RLS template).
    Idempotent via ``IF NOT EXISTS``.
    """
    name = partition_name(day)
    lo, hi = _bounds(day)
    stmts = [
        f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF {LEDGER_TABLE} "
        f"FOR VALUES FROM ('{lo}+00') TO ('{hi}+00');",
        # §5.5 per-partition index template.
        f"CREATE INDEX IF NOT EXISTS {name}_event_ix ON {name} (stream_id, event_id);",
        f"CREATE INDEX IF NOT EXISTS {name}_ws_ix ON {name} "
        f"(workspace_id, stream_id, occurred_at);",
        # §9.7 RLS on the new partition (Class T). ENABLE/FORCE are idempotent;
        # CREATE POLICY is not (no IF NOT EXISTS), so DROP-then-CREATE keeps the whole
        # statement list re-runnable — the partition manager (M-5) and a re-run over a
        # migration-created partition must not collide on the policy.
        f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {name} FORCE ROW LEVEL SECURITY;",
        f"DROP POLICY IF EXISTS tenant_isolation ON {name};",
        f"CREATE POLICY tenant_isolation ON {name} FOR ALL "
        f"USING (workspace_id = app_workspace_id()) "
        f"WITH CHECK (workspace_id = app_workspace_id());",
    ]
    return stmts


def drop_partition_sql(day: date) -> list[str]:
    """DDL to detach-then-drop one daily partition (§8.2 step 2).

    Detach keeps the parent lockless for readers, then drop. Fully idempotent: the
    DETACH runs only when the partition is still attached (Postgres has no
    ``DETACH PARTITION IF EXISTS``, so a ``pg_inherits`` guard stands in), and the
    DROP uses ``IF EXISTS``. Re-running over an already-retired day is a no-op.
    """
    name = partition_name(day)
    return [
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT 1 FROM pg_inherits "
        f"WHERE inhparent = '{LEDGER_TABLE}'::regclass "
        f"AND inhrelid = to_regclass('{name}')) THEN "
        f"ALTER TABLE {LEDGER_TABLE} DETACH PARTITION {name}; "
        "END IF; END $$;",
        f"DROP TABLE IF EXISTS {name};",
    ]


def daily_range(start: date, count: int) -> list[date]:
    """``count`` consecutive days starting at ``start`` (inclusive)."""
    return [start + timedelta(days=i) for i in range(count)]


def _execute(cursor: object, statements: Sequence[str]) -> None:
    for stmt in statements:
        cursor.execute(stmt)  # type: ignore[attr-defined]


def create_partition(cursor: object, day: date) -> str:
    """Create-and-attach the daily partition for ``day``; return its name."""
    _execute(cursor, create_partition_sql(day))
    return partition_name(day)


def drop_partition(cursor: object, day: date) -> str:
    """Detach-then-drop the daily partition for ``day``; return its name."""
    _execute(cursor, drop_partition_sql(day))
    return partition_name(day)


def ensure_partitions(cursor: object, *, start: date, days_ahead: int) -> list[str]:
    """Create-and-attach today + ``days_ahead`` daily partitions (idempotent).

    The §8.1 "Pre-created ahead" for the ledger is 3 days; the management command
    passes ``days_ahead`` accordingly. Returns the partition names touched.
    """
    names: list[str] = []
    for day in daily_range(start, days_ahead + 1):
        names.append(create_partition(cursor, day))
    return names
