"""``event_buffer`` partition DDL — the time-partitioned parent + hourly partitions
(database-schema §6.1, §8.1-8.2; delivery-channels §4.3; M-5).

``event_buffer`` is ``PARTITION BY RANGE (partition_ts)`` with **hourly**,
UTC-aligned partitions and **no DEFAULT partition** (a write outside any attached
range is a loud failure — §8.1). Django's ``CreateModel`` cannot emit a partitioned
parent, so the migration calls :func:`create_buffer_parent_sql` (raw DDL) and the
model is registered as state-only. Individual partitions are owned by the partition
manager (M-5): create-ahead a small window so a fresh DB accepts writes, drop whole
partitions older than 48 h hourly (delivery-channels §4.3, the only deletion
mechanism per ADR-0013).

Each new partition gets the §6.1 per-partition index template
(``(workspace_id, stream_id)``) and the §9.7 RLS enable/force/policy template
(belt-and-suspenders: direct-to-partition access would otherwise consult only the
partition's own policies).

Pure DDL string builders + a thin executor seam; Postgres-only (the SQLite unit
lane skips partition DDL — RLS/partitioning are Postgres constructs).
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

BUFFER_TABLE = "event_buffer"

# Physical retention: drop whole partitions older than 48 h, hourly
# (delivery-channels §4.3; database-schema §8.3). The maximum plan retention.
PHYSICAL_RETENTION_HOURS = 48
# Pre-create-ahead window: a few hours so the buffer-writer never hits an
# unattached range at the top of the hour before the beat job runs (§8.1).
CREATE_AHEAD_HOURS = 3

# The §6.1 partition-parent DDL: the full column set, the composite PK including
# the partition key, and PARTITION BY RANGE (partition_ts). Kept here (not the
# migration body) so the partition manager and the migration share one source.
_CREATE_PARENT = f"""
CREATE TABLE IF NOT EXISTS {BUFFER_TABLE} (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    workspace_id  uuid NOT NULL,
    stream_id     uuid NOT NULL,
    partition_ts  timestamptz NOT NULL,
    buffer_seq    bigint NOT NULL,
    event_id      uuid NOT NULL,
    event_type    text NOT NULL,
    occurred_at   timestamptz NOT NULL,
    emitted_at    timestamptz NOT NULL,
    -- ``text`` (not ``jsonb``) so the stored canonical JSON survives byte-for-byte:
    -- jsonb reorders object keys + normalizes numbers, which would break the S-3
    -- cross-channel byte-identity contract (BW-5: the delivered envelope is stored
    -- as canonical JSON; a REST→Kafka consumer must see identical bytes). The strip
    -- already pinned the 20-key shape; the bytes are the contract, not a queryable doc.
    envelope      text NOT NULL,
    PRIMARY KEY (stream_id, partition_ts, buffer_seq)
) PARTITION BY RANGE (partition_ts);
"""

_DROP_PARENT = f"DROP TABLE IF EXISTS {BUFFER_TABLE} CASCADE;"


def create_buffer_parent_sql() -> str:
    """The CREATE TABLE … PARTITION BY RANGE (partition_ts) parent DDL (§6.1)."""
    return _CREATE_PARENT


def drop_buffer_parent_sql() -> str:
    """Reverse: drop the partitioned parent (and all partitions, CASCADE)."""
    return _DROP_PARENT


def hour_floor(when: datetime) -> datetime:
    """The UTC hour floor of ``when`` (the partition a write at ``when`` lands in)."""
    return when.astimezone(UTC).replace(minute=0, second=0, microsecond=0)


def partition_name(hour: datetime) -> str:
    """The §8.1 partition name, e.g. ``event_buffer_p2026061014`` (UTC hour)."""
    return f"{BUFFER_TABLE}_p{hour_floor(hour):%Y%m%d%H}"


def _bounds(hour: datetime) -> tuple[str, str]:
    """UTC-aligned ``[hour, next hour)`` RANGE bounds (§8.1).

    Returned as *naive* ``YYYY-MM-DD HH:MM:SS`` strings so the partition DDL can
    append the single ``+00`` UTC offset (a tz-aware ``isoformat`` would already
    carry ``+00:00``, yielding the invalid double-offset literal Postgres rejects).
    """
    start = hour_floor(hour)
    end = start + timedelta(hours=1)
    fmt = "%Y-%m-%d %H:%M:%S"
    return start.strftime(fmt), end.strftime(fmt)


def create_partition_sql(hour: datetime) -> list[str]:
    """DDL to create-and-attach one hourly partition + its index + RLS (§8.2).

    Returns a list of statements (CREATE TABLE … PARTITION OF, the §6.1
    per-partition index, and the §9.7 RLS template). Idempotent via
    ``IF NOT EXISTS``; the policy uses DROP-then-CREATE so a re-run over a
    migration-created partition does not collide on the policy name.
    """
    name = partition_name(hour)
    lo, hi = _bounds(hour)
    return [
        f"CREATE TABLE IF NOT EXISTS {name} PARTITION OF {BUFFER_TABLE} "
        f"FOR VALUES FROM ('{lo}+00') TO ('{hi}+00');",
        # §6.1 per-partition index template.
        f"CREATE INDEX IF NOT EXISTS {name}_ws_ix ON {name} (workspace_id, stream_id);",
        # §9.7 RLS on the new partition (Class T). ENABLE/FORCE are idempotent;
        # CREATE POLICY is not, so DROP-then-CREATE keeps the list re-runnable.
        f"ALTER TABLE {name} ENABLE ROW LEVEL SECURITY;",
        f"ALTER TABLE {name} FORCE ROW LEVEL SECURITY;",
        f"DROP POLICY IF EXISTS tenant_isolation ON {name};",
        f"CREATE POLICY tenant_isolation ON {name} FOR ALL "
        f"USING (workspace_id = app_workspace_id()) "
        f"WITH CHECK (workspace_id = app_workspace_id());",
    ]


def drop_partition_sql(hour: datetime) -> list[str]:
    """DDL to detach-then-drop one hourly partition (§8.2 step 2; §4.3 retention).

    Detach keeps the parent lockless for readers, then drop. Fully idempotent: the
    DETACH runs only when the partition is still attached (Postgres has no
    ``DETACH PARTITION IF EXISTS``, so a ``pg_inherits`` guard stands in), and the
    DROP uses ``IF EXISTS``. Re-running over an already-retired hour is a no-op.
    """
    name = partition_name(hour)
    return [
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT 1 FROM pg_inherits "
        f"WHERE inhparent = '{BUFFER_TABLE}'::regclass "
        f"AND inhrelid = to_regclass('{name}')) THEN "
        f"ALTER TABLE {BUFFER_TABLE} DETACH PARTITION {name}; "
        "END IF; END $$;",
        f"DROP TABLE IF EXISTS {name};",
    ]


def hourly_range(start: datetime, count: int) -> list[datetime]:
    """``count`` consecutive UTC hours starting at ``start``'s hour (inclusive)."""
    base = hour_floor(start)
    return [base + timedelta(hours=i) for i in range(count)]


def _execute(cursor: object, statements: Sequence[str]) -> None:
    for stmt in statements:
        cursor.execute(stmt)  # type: ignore[attr-defined]


def create_partition(cursor: object, hour: datetime) -> str:
    """Create-and-attach the hourly partition for ``hour``; return its name."""
    _execute(cursor, create_partition_sql(hour))
    return partition_name(hour)


def drop_partition(cursor: object, hour: datetime) -> str:
    """Detach-then-drop the hourly partition for ``hour``; return its name."""
    _execute(cursor, drop_partition_sql(hour))
    return partition_name(hour)


def ensure_partitions(cursor: object, *, start: datetime, hours_ahead: int) -> list[str]:
    """Create-and-attach this hour + ``hours_ahead`` hourly partitions (idempotent).

    Returns the partition names touched. The partition manager beat job calls this
    each hour to keep the create-ahead window rolling (§8.1).
    """
    names: list[str] = []
    for hour in hourly_range(start, hours_ahead + 1):
        names.append(create_partition(cursor, hour))
    return names


def expired_hours(
    *, now: datetime, retention_hours: int = PHYSICAL_RETENTION_HOURS, lookback: int = 24
) -> list[datetime]:
    """Hours whose partition is older than ``retention_hours`` and droppable (§4.3).

    Scans ``lookback`` hours below the retention horizon so a delayed beat run
    still catches partitions it missed; the drop is idempotent (``IF EXISTS``).
    """
    horizon = hour_floor(now) - timedelta(hours=retention_hours)
    return [horizon - timedelta(hours=i) for i in range(1, lookback + 1)]
