# Generated by Django 5.2.15; hand-finished with the §4.4-4.5 CHECK regexes,
# Class H RLS (database-schema §9.5), and the §4.5 immutability trigger.

import django.db.models.deletion
import django.utils.timezone
import registry.domain.ids
from django.db import migrations, models

from registry.infra.rls import EnableHybridRowLevelSecurity
from registry.infra.triggers import InstallSchemaVersionImmutability, PostgresOnlyRunSQL

# database-schema §4.4 — the subject structural CHECK is a Postgres regex match
# (~), not expressible as a Django Q; applied via RunSQL (Postgres-only; no-op on
# the SQLite unit lane, where the manifest grammar + app validation carry it).
_SUBJECT_CHECK = (
    "ALTER TABLE schema_subjects ADD CONSTRAINT schema_subjects_subject_ck "
    r"CHECK (subject ~ '^[a-z][a-z0-9_]*(\.cdc)?\.[a-z][a-z0-9_]*$');"
)
_SUBJECT_CHECK_DROP = (
    "ALTER TABLE schema_subjects DROP CONSTRAINT IF EXISTS schema_subjects_subject_ck;"
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The Class H policies reference the null-safe GUC accessors
        # app_workspace_id()/app_user_id() created by tenancy's initial migration
        # (database-schema §9.3). No-op on SQLite; the ordering keeps the Postgres
        # apply correct (M-6).
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=registry.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('scenario_id', models.UUIDField()),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('compatibility_mode', models.TextField(choices=[('BACKWARD_ADDITIVE', 'Backward additive')], default='BACKWARD_ADDITIVE')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'schema_subjects',
                'constraints': [models.CheckConstraint(condition=models.Q(('compatibility_mode', 'BACKWARD_ADDITIVE')), name='schema_subjects_compat_ck'), models.UniqueConstraint(condition=models.Q(('workspace_id__isnull', True)), fields=('subject',), name='schema_subjects_global_uq'), models.UniqueConstraint(condition=models.Q(('workspace_id__isnull', False)), fields=('workspace_id', 'subject'), name='schema_subjects_ws_uq')],
            },
        ),
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.UUIDField(default=registry.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('json_schema', models.JSONField()),
                ('fingerprint', models.TextField()),
                ('compat_checked_against', models.IntegerField(blank=True, null=True)),
                ('derived_from_definition', models.UUIDField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='registry.subject')),
            ],
            options={
                'db_table': 'schema_versions',
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='schema_versions_version_ck'), models.UniqueConstraint(fields=('subject', 'version'), name='schema_versions_subject_uq'), models.UniqueConstraint(fields=('subject', 'fingerprint'), name='schema_versions_fp_uq')],
            },
        ),
        # --- §4.4 subject structural CHECK (Postgres regex; no-op on SQLite).
        # Applied as raw DDL only — not mirrored into model state (the subject
        # grammar is enforced in Python by derivation; the DB CHECK is a backstop
        # so the autodetector must not try to add/remove a matching constraint). ---
        PostgresOnlyRunSQL(sql=_SUBJECT_CHECK, reverse_sql=_SUBJECT_CHECK_DROP),
        # --- Layer 2: Class H RLS (database-schema §9.5; M-6 ships RLS with the
        # table). Global rows world-readable, writes tenant-only. No-op on SQLite.
        EnableHybridRowLevelSecurity(table='schema_subjects', model_label='registry.Subject'),
        EnableHybridRowLevelSecurity(table='schema_versions', model_label='registry.SchemaVersion'),
        # --- §4.5 immutability trigger on schema_versions (INV-REG-2). ---
        InstallSchemaVersionImmutability(),
    ]
