# Generated by Django 5.2.15 on 2026-06-13 21:48

import audit.domain.ids
import django.utils.timezone
from django.db import migrations, models

from audit.infra.rls import EnableAuditRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # The Class A audit policies reference the null-safe GUC accessors
        # app_workspace_id()/app_user_id() created by tenancy's initial migration
        # (database-schema §9.3). No-op on the SQLite test DB; the ordering keeps
        # the Postgres apply correct (M-6).
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('pk', models.CompositePrimaryKey('audit_id', 'occurred_at', blank=True, editable=False, primary_key=True, serialize=False)),
                ('audit_id', models.UUIDField(default=audit.domain.ids.uuid7, editable=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.TextField(choices=[('user', 'User'), ('api_key', 'API key'), ('system', 'System')])),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('actor_api_key_id', models.UUIDField(blank=True, null=True)),
                ('action', models.TextField()),
                ('target_type', models.TextField()),
                ('target_id', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('request_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['workspace_id', '-occurred_at'], name='audit_log_ws_ix'), models.Index(fields=['actor_user_id', '-occurred_at'], name='audit_log_user_ix')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ('user', 'api_key', 'system'))), name='audit_actor_ck'), models.CheckConstraint(condition=models.Q(models.Q(('actor_type', 'user'), ('actor_user_id__isnull', False)), models.Q(('actor_api_key_id__isnull', False), ('actor_type', 'api_key')), ('actor_type', 'system'), _connector='OR'), name='audit_actor_presence_ck')],
            },
        ),
        # --- Layer 2: Postgres Row-Level Security (database-schema §9.5 Class A;
        # M-6 ships RLS with the table). Append-only is also enforced at the grant
        # matrix (SELECT, INSERT only — database-schema §9.2). No-op on SQLite.
        EnableAuditRowLevelSecurity(model_label='audit.AuditLog'),
    ]
