# Generated by Django 5.2.15 on 2026-06-13 21:12

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
import tenancy.domain.ids
import tenancy.domain.scoping
from django.conf import settings
from django.db import migrations, models

from tenancy.infra.rls import CreateGucAccessors, EnableRowLevelSecurity


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=tenancy.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(validators=[django.core.validators.RegexValidator(message='Invalid workspace slug.', regex='^[a-z][a-z0-9-]{1,38}[a-z0-9]$')])),
                ('plan', models.TextField(choices=[('free', 'Free'), ('classroom', 'Classroom'), ('pro', 'Pro')], default='free')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateField()),
                ('events_generated', models.BigIntegerField(default=0)),
                ('events_delivered', models.BigIntegerField(default=0)),
                ('backfill_events', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, related_name='usage', to='tenancy.workspace')),
            ],
            options={
                'db_table': 'usage_counters',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=tenancy.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField(choices=[('admin', 'Admin'), ('member', 'Member')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='tenancy.workspace')),
            ],
            options={
                'db_table': 'memberships',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=tenancy.domain.ids.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('key_prefix', models.TextField(unique=True)),
                ('key_hash', models.TextField(unique=True)),
                ('last4', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, db_column='revoked_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, related_name='api_keys', to='tenancy.workspace')),
            ],
            options={
                'db_table': 'api_keys',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=tenancy.domain.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('role', models.TextField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member')),
                ('token_hash', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invited_by', models.ForeignKey(db_column='invited_by', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, related_name='invitations', to='tenancy.workspace')),
            ],
            options={
                'db_table': 'workspace_invitations',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceQuotas',
            fields=[
                ('workspace', models.OneToOneField(db_column='workspace_id', on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='quotas', serialize=False, to='tenancy.workspace')),
                ('max_members', models.IntegerField(default=3)),
                ('max_concurrent_streams', models.IntegerField(default=2)),
                ('per_stream_tps_cap', models.IntegerField(default=50)),
                ('aggregate_tps_cap', models.IntegerField(default=100)),
                ('events_per_day', models.BigIntegerField(default=1000000)),
                ('buffer_retention_hours', models.IntegerField(default=24)),
                ('backfill_max_days', models.IntegerField(default=7)),
                ('backfill_max_events', models.BigIntegerField(default=1000000)),
                ('idle_pause_minutes', models.IntegerField(default=120)),
                ('max_api_keys', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspace_quotas',
                'constraints': [models.CheckConstraint(condition=models.Q(('buffer_retention_hours__in', (24, 48))), name='ws_quotas_retention_ck')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', tenancy.domain.scoping.AllObjectsManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('name__length__gte', 1), ('name__length__lte', 100)), name='workspaces_name_len_ck'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z][a-z0-9-]{1,38}[a-z0-9]$')), name='workspaces_slug_ck'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(('plan__in', ('free', 'classroom', 'pro'))), name='workspaces_plan_ck'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), condition=models.Q(('deleted_at__isnull', True)), name='workspaces_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('workspace', 'window_date'), name='usage_counters_pk'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['workspace', 'role'], name='memberships_ws_role_ix'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('admin', 'member'))), name='memberships_role_ck'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='memberships_user_ws_uq'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['workspace'], name='api_keys_ws_ix'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(condition=models.Q(('name__length__gte', 1), ('name__length__lte', 100)), name='api_keys_name_len_ck'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(condition=models.Q(('last4__regex', '^[A-Za-z0-9]{4}$')), name='api_keys_last4_ck'),
        ),
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('admin', 'member'))), name='ws_invites_role_ck'),
        ),
        migrations.AddConstraint(
            model_name='workspaceinvitation',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('email'), condition=models.Q(('accepted_at__isnull', True)), name='ws_invites_open_uq'),
        ),
        # --- Layer 2: Postgres Row-Level Security (database-schema §9; M-6) ----
        # RLS ships in the SAME migration as the tables (M-6); the check_tenancy
        # guard requires an EnableRowLevelSecurity op per tenant table. No-op on
        # the SQLite test DB (RLS is a Postgres construct — Layer 1 + the CI
        # raw-SQL probes carry the guarantee there).
        CreateGucAccessors(),
        EnableRowLevelSecurity(table='workspaces', policy_class='W', model_label='tenancy.Workspace'),
        EnableRowLevelSecurity(table='memberships', policy_class='M', model_label='tenancy.Membership'),
        EnableRowLevelSecurity(table='workspace_invitations', policy_class='T', model_label='tenancy.WorkspaceInvitation'),
        EnableRowLevelSecurity(table='api_keys', policy_class='T', model_label='tenancy.ApiKey'),
        EnableRowLevelSecurity(table='workspace_quotas', policy_class='T', model_label='tenancy.WorkspaceQuotas'),
        EnableRowLevelSecurity(table='usage_counters', policy_class='T', model_label='tenancy.UsageCounter'),
    ]
